### PR TITLE
Fix for flaky TestGameServerAllocationMetaDataPatch

### LINKED ISSUE #725: Flaky Test: TestGameServerAllocationMetaDataPatch
I've noticed that this test occasionally fails with the following result. But it only happens sometimes.

```shell
Step #12: --- FAIL: TestGameServerAllocationMetaDataPatch (23.49s)
Step #12:     gameserverallocation_test.go:131:
Step #12:               Error Trace:    gameserverallocation_test.go:131
Step #12:               Error:          Not equal:
Step #12:                               expected: "Allocated"
Step #12:                               actual  : "UnAllocated"
Step #12:
Step #12:                               Diff:
Step #12:                               --- Expected
Step #12:                               +++ Actual
Step #12:                               @@ -1,2 +1,2 @@
Step #12:                               -(v1alpha1.GameServerAllocationState) (len=9) "Allocated"
Step #12:                               +(v1alpha1.GameServerAllocationState) (len=11) "UnAllocated"
Step #12:
Step #12:               Test:           TestGameServerAllocationMetaDataPatch
Step #12:     gameserverallocation_test.go:135:
Step #12:               Error Trace:    gameserverallocation_test.go:135
Step #12:               Error:          Expected nil, but got: &errors.errorString{s:"resource name may not be empty"}
Step #12:               Test:           TestGameServerAllocationMetaDataPatch
Step #12: time="2019-04-18 15:19:40.652" level=info msg="fleet simple-fleet-lvsfg has 3/10 ready replicas"
Step #12: time="2019-04-18 15:19:40.852" level=info msg="fleet preferred-gkfqb has 112/150 ready replicas"
```

### PR DESCRIPTION
**Pull request by markmandel**
Cache eventual consistency in the controller means that this test can be flaky. Implemented a polling request as allocation will work eventually.

Closes #725

### CODE REVIEW

File: test/e2e/gameserverallocation_test.go [hunk 1]
```diff
@@ -126,10 +126,16 @@ func TestGameServerAllocationMetaDataPatch(t *testing.T) {
 			},
 		}}
 
-	gsa, err = framework.AgonesClient.AllocationV1alpha1().GameServerAllocations(defaultNs).Create(gsa.DeepCopy())
-	if assert.Nil(t, err) {
-		assert.Equal(t, v1alpha1.GameServerAllocationAllocated, gsa.Status.State)
-	}
+	err = wait.PollImmediate(time.Second, 30*time.Second, func() (bool, error) {
+		gsa, err = framework.AgonesClient.AllocationV1alpha1().GameServerAllocations(defaultNs).Create(gsa.DeepCopy())
```
Comment (jkowalski) [inline test/e2e/gameserverallocation_test.go]: i believe this will cause panic if "err" is ever returned, because "gsa" will be set to nil and next iteration will use nill.DeepCopy()

Comment (markmandel) [reply test/e2e/gameserverallocation_test.go]: Good catch. Fixed!

**Comment by markmandel** [comment]
Gentle bump - on a mission to de-flake the CI system, and this keeps rearing it's head.
